### ISSUE TITLE
New version 0.7.0 broke our builds

### ISSUE THREAD

**Issue by wesm** [conda-forge/jpype1-feedstock#8] opened 2019-06-25 19:27 UTC
See https://issues.apache.org/jira/browse/ARROW-5728

Haven't had a chance to diagnose further but we are pinning version 0.6.3 for now

**Comment by marscher** [comment] 2019-06-25 19:42
thanks for your report. According to the JavaDoc the Int type does not have the accessed attribute. So I think it is an coincidence with the new jpype release, that your test is failing now. Refer to the apache documentation: https://arrow.apache.org/docs/java/org/apache/arrow/vector/types/pojo/class-use/ArrowType.Int.html

**Comment by marscher** [comment] 2019-06-25 19:43
@Thrameos Do you agree with me, that this should not happen, if the "isSigned" method would be in place? https://travis-ci.org/apache/arrow/jobs/550245616#L6993

**Comment by marscher** [comment] 2019-06-25 19:47
Ok, if pinning solves the problem we have to try to fix this one.

**Comment by Thrameos** [comment] 2019-06-25 19:49
The issue is that the method that should be accessed is getIsSigned according to the documentation.  The previous code would have worked either if 1) the private access bug from 0.6 series was allowing access to field. 2) or the properties customizer was activated.  

To correct this, either change the call to getIsSigned, or ``import jpype.beans`` which would activate the customizer that adds the methods as properties hack.

**Comment by marscher** [comment] 2019-06-25 19:51
The beans customizer was not used by default prior 0.7?

**Comment by Thrameos** [comment] 2019-06-25 19:51
Relevant javadoc

[ArrowType.Int](https://arrow.apache.org/docs/java/org/apache/arrow/vector/types/pojo/ArrowType.Int.html)

**Comment by Thrameos** [comment] 2019-06-25 19:54
The bean customizer was active by default but is was really buggy as it was a late load in the process, thus most classes loaded during the bootstrapping did not have the customizer (given the impression that it wasn't active).  There was a second bug that was allowing access to private fields, which conflicted with the bean property customizer as it would not customize something where there was already a field. 

Thus the only way to know what this was would be to look to see if there is a set.  The bean customizer does not allow a set without a "set*" method, but the private bug would.

**Comment by Thrameos** [comment] 2019-06-25 20:03
My current recommendation if you must support both version 0.6.3 and 0.7.0 is to add the line

```
try:
    import jpype.beans
except ImportError:
    pass
```

This would activate the buggy property customizer which should fix this type of issue, unless it was code depending on the private access bug.  I have a code work around for the private access, but as it is rather unsafe (as it means that stuff skips encapsulation entirely), I really didn't want it to be publicized solution.

**Comment by marscher** [comment] 2019-06-25 20:04
@wesm I suggest you fix the access to the method or use the beans customizer as @Thrameos suggested. I'm closing this, as it is expected behaviour in the new version.

**Closed by marscher** 2019-06-25 20:04 UTC

**Comment by wesm** [comment] 2019-06-27 21:46
Thanks. I opened https://issues.apache.org/jira/browse/ARROW-5766 about addressing your comments
